config/routes.rb
Blogger::Application.routes.draw do
  resources :posts
  
  get '/movie_names' => 'posts#find_by_prefixes'
  
  
  get '/request_form' => 'web_services#request_form'
  
  post '/send_request' => "web_services#send_request", defaults: {format: :json}

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
require 'csv'
require 'open-uri'
require 'redis'
require 'json'


class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  caches_page :index, :show
  
  
  def internet_connection?
    begin
      true if open("http://www.google.com/")
    rescue
      false
    end
  end

  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end


  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    #raise params[:post].inspect
    @post = Post.new(params[:post])
    if internet_connection?
      respond_to do |format|
        if @post.save
          format.html { redirect_to @post, notice: 'Post was successfully created.' }
          format.json { render json: @post, status: :created, location: @post }
        else
          format.html { render action: "new" }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    else
      CSV.open('articles.csv', 'w') do |csv|
        params[:post].each {|record| csv << record }
      end
    end  
    
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
  
  def find_by_prefixes
    prefixes = []
    prefixes << params["term"]
    
    intersection_key = index_key_for(prefixes)
    
    index_keys       = prefixes.map {|prefix| index_key_for(prefix)}
    
    $redis.zinterstore(intersection_key, index_keys)
    $redis.expire(intersection_key, 7200)

    data_hash_keys  = $redis.zrevrange(intersection_key, 0, -1)
    
    matching_movies = $redis.hmget(data_key, *data_hash_keys)
    
    matching_movies.map {|movie| JSON.parse(movie, symbolize_names: true)}
    
    matching_movies_parsed_json =  matching_movies.map{|x| JSON.parse(x)}
    
    final_matching_movies = matching_movies_parsed_json.map{|x| x["name"]}
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: matching_movies_parsed_json }
    end
  end
  
 private
  
  def data_key
    "moviesearch:data"
  end

  def index_key
    "moviesearch:index"
  end
    
  def index_key_for(prefix)
    "#{index_key}:#{prefix}"
  end
  
end

app/controllers/web_services_controller.rb
require 'cassandra'

class WebServicesController < ApplicationController
  

  def request_form
  
  end
  
  def send_request
    @ori = params[:ori]
    results = search_database(@ori)
    if results.present?
      extract_stop_data
      render :send_request, status: :sent_rquest
    end
  end
  
  def cassandra_connect 
    cluster = Cassandra.cluster(hosts: "ec2-13-58-26-103.us-east-2.compute.amazonaws.com")
    session  = cluster.connect('ab953')  
  end
  
  def search_database(ori)
    @ori = ori
    session = cassandra_connect
    info = session.execute("SELECT * FROM stops_by_ori_reason where ori='#{@ori}'").execution_info
  end
  
  def extract_stop_data
    
    #session = cassandra_connect
    #info = session.execute("SELECT stop_duration, date_time FROM stops_by_ori_reason where ori='#{@ori}'") 
  end
  
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/web_services_helper.rb
module WebServicesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag 'jquery.min', 'jquery-ui.min.js' %>
  <%= stylesheet_link_tag 'jquery-ui.min.css' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  
  <input type="text" name="term" class="auto_search_complete">
  
  <div class="actions">
    <%= f.submit %>
  </div>
  
  
<% end %>


<script type="text/javascript">

$('.auto_search_complete').autocomplete({
  minLength: 3,
  delay: 600,
  source: function(request, response) {
    $.ajax({
      url: "/movie_names",
      dataType: "json",
      data: {term: request.term},
      success: function( data ) {
        
        response($.map(data, function (item) {
                                return {
                                    label: item.label,
                                    value: item.name
                                }
                            }));
      }
    });
  }        
});

</script>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.body %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Body:</b>
  <%= @post.body %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/web_services/request_form.html.erb
<h3> Personal Information </h3>

<%= form_tag(send_request_path) do %>
  <label>ORI </label>
  <%= text_field_tag :ori %></br></br>
  
  <label>Stop Date </label>
  <%= text_field_tag :stop_date %></br></br>
  
  <label>Stop Time</label>
  <%= text_field_tag :stop_time %></br></br>
  
  <label>Stop Duration</label>
  <%= text_field_tag :stop_duration %></br></br>
  
  <label>Closest City </label>
  <%= text_field_tag :closestcity %></br></br>
  
  <label>K-Reason for Stop </label>
  <%= text_field_tag :k_reasonforstop %></br></br>

  <label>Perception Data</label>
  <select>
  <option value="Asian">Asian</option>
  <option value="-Black-AfricanAmer">-Black-AfricanAmer"</option>
  <option value="midEasternSouthAsian">midEasternSouthAsian</option>
  <option value="White">White</option> 
</select> </br></br>
  
  <label>suspicion Drugtxn </label>
  <%= text_field_tag :suspiciondrugtxn %></br></br>
  
  <label>Basis for Property Seizure </label>
  <%= text_field_tag :basisforpropertyseizure %></br></br>
  
  <label>Results of Stop </label>
  <%= text_field_tag :resultsof_stop %></br></br>



  
  <%= submit_tag "Submit" %>
<% end %>